name: Day 3 Scan

on:
  push:
    branches:
      - master
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
    
    - name: Remove existing Conda env
      run: | 
        conda env remove -n conda_end || true
      shell: bash

    - name: Create and Activate Conda environment
      run: | 
        conda env create -f conda_env.yml
        conda init bash
        source ~/.bashrc
        conda activate conda_env
        python3 src/main.py -biosample synthetic -k 35
      shell: bash